version: '3.3'

networks:
  d_bridge:
    driver: bridge
  d_isolated: 
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.18.0.0/24

services:
  seeder:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      d_isolated:
        ipv4_address: 172.18.0.2
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  leecher:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      d_isolated:
        ipv4_address: 172.18.0.3
    stdin_open: true # docker run -i
    tty: true        # docker run -t